### ISSUE TITLE
includes and non includes

### ISSUE THREAD

**Issue by PramUkesh** [Soverance/EtherealLegends#18]
so some files are not included in the source code please state those
1. if they are available in market place or you build them own
2. what assets are not included, name them and where they present in your project
3. Any additional points state here

**Comment by smccutchen** [comment]
As stated in this repo's readme:

"_While I'd love to completely open-source Ethereal Legends, significant portions of the code used to create the full game is currently within UE4's Blueprint system, and of course I do not have the rights to redistribute any of the assets I've used to create the game. So this repository is the best I can do, providing you with the direct source I've used to build the game's foundation._"

This repo for _Ethereal Legends_ is source-code only.  It comprises approximately 40% of the game's underlying structure.  This repo includes no assets whatsoever, nor does it contain any project-specific files (_such as the .uproject, .sln, config files, etc_).  Everything you might find in the "Content" directory of a UE4 project is missing.  It is strictly source code found in the "Source" directory of the full UE4 project, uploaded here and meant as a learning resource and reference material.  **This repository is not meant for end-users to be able to freely play or modify the full game.**

The list of missing assets is far too long to compile and include anywhere.  There are literally _thousands_ of them.  The assets used to create Ethereal Legends are mixed between things I sourced freely from UE4 tutorial content, things I purchased from online marketplaces, things I had custom-made by external artists, and things I made myself.  For the majority of assets, I do not have the rights to redistribute them in source form, and therefore they cannot legally be added to this repo.
